# Generated by Django 5.1.3 on 2026-04-03 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Simulacro')),
                ('soluciones_s1', models.CharField(max_length=150, verbose_name='Soluciones Sesión 1 (120 ítems)')),
                ('soluciones_s2', models.CharField(max_length=150, verbose_name='Soluciones Sesión 2 (134 ítems)')),
                ('puntos_corte_s1', models.JSONField(default=dict, verbose_name='Puntos de Corte Sesión 1')),
                ('puntos_corte_s2', models.JSONField(default=dict, verbose_name='Puntos de Corte Sesión 2')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Simulacro',
                'verbose_name_plural': 'Simulacros',
            },
        ),
        migrations.CreateModel(
            name='ResultadoSimulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas_s1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Respuestas extraídas S1')),
                ('respuestas_s2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Respuestas extraídas S2')),
                ('puntaje_global', models.FloatField(default=0.0, verbose_name='Puntaje Global')),
                ('fecha_calificacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_simulacros', to=settings.AUTH_USER_MODEL, verbose_name='Alumno')),
                ('simulacro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='simulacros.simulacro', verbose_name='Simulacro')),
            ],
            options={
                'verbose_name': 'Resultado de Simulacro',
                'verbose_name_plural': 'Resultados de Simulacros',
                'unique_together': {('alumno', 'simulacro')},
            },
        ),
    ]
