# Generated by Django 5.1.3 on 2026-04-03 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosimulacro',
            name='fecha_realizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de realización'),
        ),
        migrations.AddField(
            model_name='resultadosimulacro',
            name='registrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacros_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrador'),
        ),
    ]
