# Generated by Django 5.1.3 on 2026-04-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0035_merge_0034_alter_alumno_estado_0034_alumno_vendedor'),
        ('simulacros', '0002_resultadosimulacro_fecha_realizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosimulacro',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_simulacros', to='academico.alumno', verbose_name='Alumno'),
        ),
    ]
