# Generated by Django 5.1.3 on 2026-04-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacros', '0003_alter_resultadosimulacro_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosimulacro',
            name='puntaje_ingles',
            field=models.FloatField(default=0.0, verbose_name='Inglés'),
        ),
        migrations.AddField(
            model_name='resultadosimulacro',
            name='puntaje_lectura',
            field=models.FloatField(default=0.0, verbose_name='Lectura Crítica'),
        ),
        migrations.AddField(
            model_name='resultadosimulacro',
            name='puntaje_matematicas',
            field=models.FloatField(default=0.0, verbose_name='Matemáticas'),
        ),
        migrations.AddField(
            model_name='resultadosimulacro',
            name='puntaje_naturales',
            field=models.FloatField(default=0.0, verbose_name='Ciencias Naturales'),
        ),
        migrations.AddField(
            model_name='resultadosimulacro',
            name='puntaje_sociales',
            field=models.FloatField(default=0.0, verbose_name='Sociales y Ciudadanas'),
        ),
    ]
