# Generated by Django 5.1.15 on 2026-04-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulacros", "0005_simulacro_componentes_s1_s2"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultadosimulacro",
            name="puntaje_global_modificado",
            field=models.FloatField(
                default=0.0, verbose_name="Puntaje Global Modificado"
            ),
        ),
        migrations.AddField(
            model_name="resultadosimulacro",
            name="puntaje_ingles_modificado",
            field=models.FloatField(default=0.0, verbose_name="Inglés Modificado"),
        ),
        migrations.AddField(
            model_name="resultadosimulacro",
            name="puntaje_lectura_modificado",
            field=models.FloatField(
                default=0.0, verbose_name="Lectura Crítica Modificado"
            ),
        ),
        migrations.AddField(
            model_name="resultadosimulacro",
            name="puntaje_matematicas_modificado",
            field=models.FloatField(default=0.0, verbose_name="Matemáticas Modificado"),
        ),
        migrations.AddField(
            model_name="resultadosimulacro",
            name="puntaje_naturales_modificado",
            field=models.FloatField(
                default=0.0, verbose_name="Ciencias Naturales Modificado"
            ),
        ),
        migrations.AddField(
            model_name="resultadosimulacro",
            name="puntaje_sociales_modificado",
            field=models.FloatField(
                default=0.0, verbose_name="Sociales y Ciudadanas Modificado"
            ),
        ),
        migrations.AddField(
            model_name="simulacro",
            name="umbral",
            field=models.IntegerField(
                default=200,
                help_text="Puntaje global mínimo aceptable. Los puntajes menores se ajustarán dinámicamente.",
                verbose_name="Umbral de Puntaje Mínimo",
            ),
        ),
    ]
