# Generated by Django 5.1.3 on 2026-07-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacros', '0006_resultadosimulacro_puntaje_global_modificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacro',
            name='boost_max',
            field=models.IntegerField(default=12, help_text='Incremento aleatorio máximo para sumar al objetivo base.', verbose_name='Boost Máximo'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='boost_min',
            field=models.IntegerField(default=6, help_text='Incremento aleatorio mínimo para sumar al objetivo base.', verbose_name='Boost Mínimo'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='objetivo_1',
            field=models.IntegerField(default=245, help_text='Objetivo base asignado si el puntaje global es menor o igual a Umbral 1.', verbose_name='Objetivo Base 1'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='objetivo_2',
            field=models.IntegerField(default=280, help_text='Objetivo base asignado si el puntaje global está entre Umbral 1 + 1 y Umbral 2.', verbose_name='Objetivo Base 2'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='objetivo_3',
            field=models.IntegerField(default=310, help_text='Objetivo base asignado si el puntaje global es mayor que Umbral 2.', verbose_name='Objetivo Base 3'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='umbral_1',
            field=models.IntegerField(default=140, help_text='Puntaje global real para el primer rango (inclusive).', verbose_name='Umbral 1'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='umbral_2',
            field=models.IntegerField(default=240, help_text='Puntaje global real para el segundo rango (inclusive).', verbose_name='Umbral 2'),
        ),
    ]
