# Generated by Django 5.1.3 on 2026-07-24 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0037_alter_alumno_tipo_programa'),
        ('simulacros', '0007_simulacro_boost_max_simulacro_boost_min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacroDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Simulacro Diagnóstico')),
                ('soluciones', models.CharField(max_length=150, verbose_name='Soluciones (90 ítems)')),
                ('puntos_corte', models.JSONField(blank=True, default=dict, help_text='Ejemplo: {"cortes": [18, 36, 54, 72]}', verbose_name='Puntos de Corte')),
                ('umbral', models.IntegerField(default=200, help_text='Puntaje global mínimo aceptable.', verbose_name='Umbral de Puntaje Mínimo')),
                ('umbral_1', models.IntegerField(default=140, verbose_name='Umbral 1')),
                ('objetivo_1', models.IntegerField(default=245, verbose_name='Objetivo Base 1')),
                ('umbral_2', models.IntegerField(default=240, verbose_name='Umbral 2')),
                ('objetivo_2', models.IntegerField(default=280, verbose_name='Objetivo Base 2')),
                ('objetivo_3', models.IntegerField(default=310, verbose_name='Objetivo Base 3')),
                ('boost_min', models.IntegerField(default=6, verbose_name='Boost Mínimo')),
                ('boost_max', models.IntegerField(default=12, verbose_name='Boost Máximo')),
                ('componentes', models.JSONField(blank=True, default=list, help_text='Lista ordenada de componentes. Ejemplo: ["matematicas", "lectura", "sociales", "naturales", "ingles"].', verbose_name='Orden de componentes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Simulacro Diagnóstico',
                'verbose_name_plural': 'Simulacros Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='ResultadoSimulacroDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.CharField(blank=True, max_length=150, null=True, verbose_name='Respuestas extraídas (90 ítems)')),
                ('puntaje_global', models.FloatField(default=0.0, verbose_name='Puntaje Global')),
                ('puntaje_matematicas', models.FloatField(default=0.0, verbose_name='Matemáticas')),
                ('puntaje_lectura', models.FloatField(default=0.0, verbose_name='Lectura Crítica')),
                ('puntaje_sociales', models.FloatField(default=0.0, verbose_name='Sociales y Ciudadanas')),
                ('puntaje_naturales', models.FloatField(default=0.0, verbose_name='Ciencias Naturales')),
                ('puntaje_ingles', models.FloatField(default=0.0, verbose_name='Inglés')),
                ('puntaje_global_modificado', models.FloatField(default=0.0, verbose_name='Puntaje Global Modificado')),
                ('puntaje_matematicas_modificado', models.FloatField(default=0.0, verbose_name='Matemáticas Modificado')),
                ('puntaje_lectura_modificado', models.FloatField(default=0.0, verbose_name='Lectura Crítica Modificado')),
                ('puntaje_sociales_modificado', models.FloatField(default=0.0, verbose_name='Sociales y Ciudadanas Modificado')),
                ('puntaje_naturales_modificado', models.FloatField(default=0.0, verbose_name='Ciencias Naturales Modificado')),
                ('puntaje_ingles_modificado', models.FloatField(default=0.0, verbose_name='Inglés Modificado')),
                ('fecha_realizacion', models.DateField(blank=True, null=True, verbose_name='Fecha de realización')),
                ('fecha_calificacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_simulacros_diagnosticos', to='academico.alumno', verbose_name='Alumno')),
                ('registrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacros_diagnosticos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrador')),
                ('simulacro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='simulacros.simulacrodiagnostico', verbose_name='Simulacro Diagnóstico')),
            ],
            options={
                'verbose_name': 'Resultado de Simulacro Diagnóstico',
                'verbose_name_plural': 'Resultados de Simulacros Diagnósticos',
                'unique_together': {('alumno', 'simulacro')},
            },
        ),
    ]
