# Generated by Django 5.1.3 on 2026-10-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacros', '0008_simulacrodiagnostico_resultadosimulacrodiagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacro',
            name='mostrar_puntaje_real',
            field=models.BooleanField(default=False, help_text='Si está activo, en la consulta de estudiante y el PDF descargable se mostrarán los puntajes reales en lugar de los modificados.', verbose_name='Mostrar Puntaje Real a Estudiantes'),
        ),
        migrations.AddField(
            model_name='simulacrodiagnostico',
            name='mostrar_puntaje_real',
            field=models.BooleanField(default=False, help_text='Si está activo, en la consulta de estudiante y el PDF descargable se mostrarán los puntajes reales en lugar de los modificados.', verbose_name='Mostrar Puntaje Real a Estudiantes'),
        ),
    ]
