# Generated by Django 5.1.3 on 2025-02-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_alter_alumno_identificacion'),
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deuda', to='academico.alumno'),
        ),
    ]
