# Generated by Django 5.1.3 on 2025-03-09 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_alter_deuda_alumno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='estado',
            field=models.CharField(choices=[('emitida', 'Emitida'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='emitida', help_text='Estado actual de la deuda.', max_length=20),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la deuda.'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo pendiente de la deuda.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, help_text='Valor total de la deuda.', max_digits=10),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total de la cuota.', max_digits=10)),
                ('monto_abonado', models.DecimalField(decimal_places=2, default=0, help_text='Monto abonado hasta la fecha.', max_digits=10)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la cuota.')),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('pagada_parcial', 'Pagada Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='emitida', help_text='Estado actual de la cuota.', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], help_text='Método de pago utilizado.', max_length=20, null=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='cartera.deuda')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='cartera.deuda')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(help_text='Número único del recibo.', max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, help_text='Fecha de emisión del recibo.')),
                ('monto_abonado', models.DecimalField(decimal_places=2, help_text='Monto abonado en este recibo.', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], help_text='Método de pago utilizado.', max_length=20)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='cartera.cuota')),
            ],
        ),
        migrations.DeleteModel(
            name='Abono',
        ),
    ]
