# Generated by Django 5.1.3 on 2025-03-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0003_alter_deuda_estado_alter_deuda_fecha_creacion_and_more'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Egresos',
            new_name='Egreso',
        ),
    ]
