# Generated by Django 5.1.3 on 2025-03-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0004_rename_egresos_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='estado',
            field=models.CharField(choices=[('emitida', 'Emitida'), ('pagada', 'Pagada')], default='emitida', help_text='Estado actual de la deuda.', max_length=20),
        ),
    ]
