# Generated by Django 5.1.3 on 2025-03-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0005_alter_deuda_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaRecaudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.IntegerField()),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-anio', 'mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
