# Generated by Django 5.1.3 on 2025-04-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_metarecaudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('datáfono', 'Datáfono')], help_text='Método de pago utilizado.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('datáfono', 'Datáfono')], help_text='Método de pago utilizado.', max_length=20),
        ),
    ]
