# Generated by Django 5.1.3 on 2025-04-12 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0007_alter_cuota_metodo_pago_alter_recibo_metodo_pago'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='ubicaciones.municipio'),
        ),
    ]
