# Generated by Django 5.1.3 on 2025-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0008_egreso_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para esta tarifa', max_length=100)),
                ('tipo_dia', models.IntegerField(choices=[(0, 'Lunes a Viernes'), (1, 'Sábado'), (2, 'Domingo')], help_text='Tipo de día al que aplica esta tarifa')),
                ('horario', models.CharField(blank=True, choices=[('08:00-10:00', '8:00 AM - 10:00 AM'), ('10:00-12:00', '10:00 AM - 12:00 PM'), ('14:00-17:00', '2:00 PM - 5:00 PM'), ('15:00-17:30', '3:00 PM - 5:30 PM'), ('18:45-20:45', '6:45 PM - 8:45 PM'), ('08:00-12:00', '8:00 AM - 12:00 PM (Medio Simulacro)'), ('08:00-17:00', '8:00 AM - 5:00 PM (Simulacro Completo)'), ('07:00-14:00', '7:00 AM - 2:00 PM (Jornada Especial Colegios)')], help_text='Horario al que aplica esta tarifa', max_length=20, null=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor a pagar por la clase en pesos colombianos', max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si esta tarifa está activa actualmente')),
            ],
            options={
                'verbose_name': 'Tarifa de clase',
                'verbose_name_plural': 'Tarifas de clases',
                'ordering': ['-activa', 'tipo_dia', 'horario'],
                'unique_together': {('tipo_dia', 'horario', 'activa')},
            },
        ),
    ]
