# Generated by Django 5.1.3 on 2025-05-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0009_tarifaclase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifaclase',
            name='horario',
            field=models.CharField(blank=True, choices=[('08:00-11:00', '8:00 AM - 11:00 AM'), ('14:00-17:00', '2:00 PM - 5:00 PM'), ('08:00-10:00', '8:00 AM - 10:00 AM'), ('10:00-12:00', '10:00 AM - 12:00 PM'), ('15:00-17:30', '3:00 PM - 5:30 PM'), ('18:45-20:45', '6:45 PM - 8:45 PM'), ('08:00-12:00', '8:00 AM - 12:00 PM (Medio Simulacro)'), ('08:00-17:00', '8:00 AM - 5:00 PM (Simulacro Completo)'), ('07:00-14:00', '7:00 AM - 2:00 PM (Jornada Especial Colegios)')], help_text='Horario al que aplica esta tarifa', max_length=20, null=True),
        ),
    ]
