# Generated by Django 5.1.3 on 2025-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0010_alter_tarifaclase_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se realizó el pago efectivamente.', null=True),
        ),
    ]
