# Generated by Django 5.1.3 on 2025-05-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0011_cuota_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='concepto',
            field=models.CharField(choices=[('nomina_profesores', 'Nómina profesores'), ('nomina_administrativos', 'Nómina administrativos'), ('servicios_publicos', 'Servicios públicos'), ('servicio_tecnico_pc', 'Servicio técnico PC'), ('servicio_tecnico_fotocopias', 'Servicio técnico fotocopias'), ('arreglo_planta_fisica', 'Arreglo planta física'), ('adquisiciones', 'Adquisiciones'), ('viaticos', 'Viáticos'), ('otros', 'Otros')], default='servicio_tecnico_pc', max_length=100),
        ),
    ]
