# Generated by Django 5.1.3 on 2025-06-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0012_alter_egreso_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='tipo',
            field=models.CharField(choices=[('preicfes_privado', 'PreICFES Privado'), ('preicfes_publico', 'PreICFES Público'), ('politecnico', 'Politécnico'), ('semillero', 'Semillero de investigación')], default='preicfes_privado', help_text='Tipo de programa al que pertenece la deuda.', max_length=20),
        ),
    ]
