# Generated by Django 5.1.3 on 2025-06-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0013_deuda_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deuda',
            name='tipo',
        ),
        migrations.AddField(
            model_name='deuda',
            name='edicion_habilitada',
            field=models.BooleanField(default=False, help_text='Indica si la deuda puede ser editada.'),
        ),
    ]
