# Generated by Django 5.1.3 on 2025-08-22 22:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0014_remove_deuda_tipo_deuda_edicion_habilitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='concepto',
            field=models.CharField(choices=[('nomina_profesores', 'Nómina profesores'), ('nomina_administrativos', 'Nómina administrativos'), ('arriendo', 'Arriendo'), ('nomina_vendedoras', 'Nómina vendedoras'), ('nomina_auxiliares', 'Nómina auxiliares'), ('servicios_publicos', 'Servicios públicos'), ('servicio_tecnico_pc', 'Servicio técnico PC'), ('servicio_tecnico_fotocopias', 'Servicio técnico fotocopias'), ('publicidad', 'Publicidad'), ('arreglo_planta_fisica', 'Arreglo planta física'), ('adquisiciones', 'Adquisiciones'), ('viaticos', 'Viáticos'), ('otros', 'Otros')], default='servicio_tecnico_pc', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarifaclase',
            name='horario',
            field=models.CharField(blank=True, choices=[('08:00-11:00', '8:00 AM - 11:00 AM'), ('14:00-17:00', '2:00 PM - 5:00 PM'), ('08:00-10:00', '8:00 AM - 10:00 AM'), ('10:00-12:00', '10:00 AM - 12:00 PM'), ('15:00-17:30', '3:00 PM - 5:30 PM'), ('18:45-20:45', '6:45 PM - 8:45 PM'), ('13:30-15:30', '1:30 PM - 3:30 PM'), ('15:30-17:30', '3:30 PM - 5:30 PM'), ('08:00-12:00', '8:00 AM - 12:00 PM (Medio Simulacro)'), ('08:00-17:00', '8:00 AM - 5:00 PM (Simulacro Completo)'), ('07:00-14:00', '7:00 AM - 2:00 PM (Jornada Especial Colegios)')], help_text='Horario al que aplica esta tarifa', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AcuerdoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acuerdo', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se crea el acuerdo.')),
                ('fecha_prometida_pago', models.DateField(help_text='Fecha en que el alumno se compromete a pagar.')),
                ('nota', models.TextField(blank=True, help_text='Observaciones sobre el acuerdo.', null=True)),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('cumplido', 'Cumplido'), ('incumplido', 'Incumplido')], default='emitido', max_length=20)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='cartera.cuota')),
            ],
            options={
                'verbose_name': 'Acuerdo de Pago',
                'verbose_name_plural': 'Acuerdos de Pago',
                'ordering': ['-fecha_prometida_pago'],
            },
        ),
    ]
