# Generated by Django 5.1.3 on 2026-03-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0016_alter_tarifaclase_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='editado_por',
            field=models.CharField(blank=True, help_text='Username del usuario que realizó la última edición.', max_length=150, null=True, verbose_name='Editado por'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última edición.', null=True, verbose_name='Fecha de edición'),
        ),
    ]
