# Generated by Django 5.1.3 on 2026-07-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0017_cuota_editado_por_cuota_fecha_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='soporte_pago',
            field=models.ImageField(blank=True, help_text='Imagen de soporte o comprobante de la transacción de pago.', null=True, upload_to='soportes_cuotas/%Y/%m/%d/', verbose_name='Soporte de Pago'),
        ),
    ]
