# Generated by Django 5.1.15 on 2026-05-24 20:28

import django.db.models.deletion
import django.utils.timezone
import ventas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_padre_madre', models.CharField(max_length=150, verbose_name='Nombre Padre/Madre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('nombre_estudiante', models.CharField(max_length=150, verbose_name='Nombre del Estudiante')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor / Autor')),
            ],
            options={
                'verbose_name': 'Preventa',
                'verbose_name_plural': 'Preventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de la Incidencia')),
                ('etapa', models.CharField(choices=[('contacto_inicial', 'Contacto Inicial'), ('presentacion', 'Presentación del Servicio'), ('seguimiento', 'Seguimiento'), ('cierre_exitoso', 'Cierre Exitoso / Matriculado'), ('descartado', 'Descartado')], default='contacto_inicial', max_length=50, verbose_name='Etapa')),
                ('texto', models.TextField(verbose_name='Detalle de la Incidencia')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=ventas.models.incidencia_upload_path, verbose_name='Imagen de Evidencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('preventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='ventas.preventa', verbose_name='Preventa Asociada')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha'],
            },
        ),
    ]
