# Generated by Django 5.1.15 on 2026-05-24 21:00

import django.db.models.deletion
import ventas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_preventa_incidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='imagen',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IncidenciaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=ventas.models.incidencia_imagen_upload_path, verbose_name='Imagen de Evidencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ventas.incidencia', verbose_name='Incidencia')),
            ],
            options={
                'verbose_name': 'Imagen de Incidencia',
                'verbose_name_plural': 'Imágenes de Incidencia',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
