# Generated by Django 5.1.3 on 2026-03-01 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0002_initial'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intentosimulacro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_simulacro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intentosesion',
            name='intento_simulacro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_sesion', to='evaluaciones.intentosimulacro'),
        ),
        migrations.AddField(
            model_name='intentotaller',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_taller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='curriculo.tema'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='imagenpregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='preguntasimulacro',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_componente', to='evaluaciones.componentesesion'),
        ),
        migrations.AddField(
            model_name='preguntasimulacro',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='preguntataller',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='respuestasimulacro',
            name='intento_sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.intentosesion'),
        ),
        migrations.AddField(
            model_name='respuestasimulacro',
            name='opcion_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.opcion'),
        ),
        migrations.AddField(
            model_name='respuestasimulacro',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='respuestataller',
            name='intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.intentotaller'),
        ),
        migrations.AddField(
            model_name='respuestataller',
            name='opcion_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.opcion'),
        ),
        migrations.AddField(
            model_name='respuestataller',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='intentosesion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.sesionsimulacro'),
        ),
        migrations.AddField(
            model_name='componentesesion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='evaluaciones.sesionsimulacro'),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacros', to='curriculo.modulo'),
        ),
        migrations.AddField(
            model_name='sesionsimulacro',
            name='simulacro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='evaluaciones.simulacro'),
        ),
        migrations.AddField(
            model_name='intentosimulacro',
            name='simulacro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.simulacro'),
        ),
        migrations.AddField(
            model_name='taller',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres', to='curriculo.modulo'),
        ),
        migrations.AddField(
            model_name='taller',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres', to='curriculo.tema'),
        ),
        migrations.AddField(
            model_name='preguntataller',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_taller', to='evaluaciones.taller'),
        ),
        migrations.AddField(
            model_name='intentotaller',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='evaluaciones.taller'),
        ),
    ]
