# Generated by Django 5.1.3 on 2026-03-01 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacros_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taller',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
