# Generated by Django 4.2.16 on 2026-03-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('oculto', 'Oculto')], default='borrador', max_length=20),
        ),
    ]
