# Generated by Django 4.2.16 on 2026-05-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_taller_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text="Título opcional (ej: 'Texto 1', 'Lectura A').", max_length=255)),
                ('texto', models.TextField(blank=True, help_text='Contenido HTML del bloque (acepta negritas, cursivas, etc.).')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloque de Contexto',
                'verbose_name_plural': 'Bloques de Contexto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evaluaciones/contextos/')),
                ('descripcion', models.CharField(blank=True, help_text="Ej: 'Figura 1'", max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='evaluaciones.bloquecontexto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='bloque_contexto',
            field=models.ForeignKey(blank=True, help_text='Bloque de lectura/contexto que precede a esta pregunta (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='evaluaciones.bloquecontexto'),
        ),
    ]
