# Generated by Django 4.2.16 on 2026-05-07 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_remove_clasevirtual_fecha_programada_and_more'),
        ('evaluaciones', '0004_bloque_contexto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloquecontexto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='bloquecontexto',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Materia a la que pertenece este contexto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques_contexto', to='curriculo.materia'),
        ),
    ]
