# Generated by Django 4.2.16 on 2026-05-10 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones', '0005_remove_bloquecontexto_titulo_bloquecontexto_materia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intentosimulacro',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='simulacro',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveField(
            model_name='simulacro',
            name='fecha_apertura',
        ),
        migrations.RemoveField(
            model_name='simulacro',
            name='fecha_cierre',
        ),
        migrations.AddField(
            model_name='intentosimulacro',
            name='tiempo_empleado_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulacro',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='intentosesion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_sesion', to='evaluaciones.sesionsimulacro'),
        ),
        migrations.AlterField(
            model_name='intentosimulacro',
            name='resultados_detallados',
            field=models.JSONField(blank=True, help_text='Lista: [{materia_nombre, correctas, total, porcentaje, peso}]', null=True),
        ),
        migrations.AlterField(
            model_name='intentosimulacro',
            name='simulacro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='evaluaciones.simulacro'),
        ),
        migrations.AlterField(
            model_name='sesionsimulacro',
            name='nombre',
            field=models.CharField(help_text='Ej: Sesión 1 — Mañana', max_length=100),
        ),
        migrations.AlterField(
            model_name='simulacro',
            name='duracion_minutos',
            field=models.PositiveIntegerField(help_text='Tiempo máximo por sesión en minutos (se pasa al cronómetro del frontend).'),
        ),
        migrations.CreateModel(
            name='VentanaSimulacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(help_text='Cuándo se abre el simulacro para los estudiantes.')),
                ('fecha_cierre', models.DateTimeField(help_text='Cuándo se cierra definitivamente.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventanas_simulacro_creadas', to=settings.AUTH_USER_MODEL)),
                ('simulacro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventanas', to='evaluaciones.simulacro')),
            ],
            options={
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='intentosimulacro',
            name='ventana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos', to='evaluaciones.ventanasimulacro'),
        ),
    ]
