# Generated by Django 4.2.16 on 2026-05-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_alter_intentosimulacro_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentesesion',
            name='materia',
        ),
        migrations.AddField(
            model_name='componentesesion',
            name='nombre',
            field=models.CharField(default='Componente Genérico', help_text='Ej: Matemáticas, Ciencias Naturales', max_length=100),
            preserve_default=False,
        ),
    ]
