# Generated by Django 4.2.16 on 2026-05-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_remove_componentesesion_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Matemáticas, Ciencias Naturales, Lectura Crítica', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='componentesesion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='componentesesion',
            name='componente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.componente'),
            preserve_default=False,
        ),
    ]
