# Generated by Django 5.1.3 on 2026-06-29 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0008_componente_remove_componentesesion_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='intentosimulacro',
            index=models.Index(fields=['usuario', 'simulacro'], name='evaluacione_usuario_f7b92a_idx'),
        ),
        migrations.AddIndex(
            model_name='intentosimulacro',
            index=models.Index(fields=['fecha_fin'], name='evaluacione_fecha_f_ba3a44_idx'),
        ),
        migrations.AddIndex(
            model_name='intentotaller',
            index=models.Index(fields=['usuario', 'taller'], name='evaluacione_usuario_06be26_idx'),
        ),
        migrations.AddIndex(
            model_name='intentotaller',
            index=models.Index(fields=['fecha_fin'], name='evaluacione_fecha_f_492a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestasimulacro',
            index=models.Index(fields=['intento_sesion'], name='evaluacione_intento_fa53ee_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestataller',
            index=models.Index(fields=['intento'], name='evaluacione_intento_b5668f_idx'),
        ),
    ]
