# Generated by Django 5.1.3 on 2026-07-06 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0005_alter_modulo_ciclo'),
        ('evaluaciones', '0009_intentosimulacro_evaluacione_usuario_f7b92a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='curriculo.modulo')),
            ],
            options={
                'verbose_name': 'Actividad Virtual',
                'verbose_name_plural': 'Actividades Virtuales',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='BloqueActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('drag_drop', 'Drag & Drop (palabras a huecos)'), ('fill_dropdown', 'Rellenar con desplegable'), ('fill_type', 'Completar escribiendo'), ('audio_task', 'Tarea de Audio')], max_length=20)),
                ('consigna', models.TextField(help_text='Instrucciones para este bloque de ejercicios')),
                ('contenido', models.TextField(help_text='Texto con corchetes [palabra] o [opcion1|opcion2]')),
                ('distractores', models.CharField(blank=True, help_text='Opciones falsas separadas por comas (solo Drag & Drop)', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='evaluaciones.actividadvirtual')),
            ],
            options={
                'verbose_name': 'Bloque de Actividad',
                'verbose_name_plural': 'Bloques de Actividad',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='IntentoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(help_text='Respuestas de texto estructuradas: {bloque_id: {gap_idx: valor}}')),
                ('retroalimentacion', models.JSONField(blank=True, help_text='Retroalimentación automática por bloque', null=True)),
                ('puntaje', models.FloatField(blank=True, help_text='Nota del intento de 0 a 100', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='evaluaciones.actividadvirtual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Actividad',
                'verbose_name_plural': 'Intentos de Actividad',
            },
        ),
        migrations.CreateModel(
            name='IntentoAudioBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='ingles/audios/%Y/%m/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('comentario_profe', models.TextField(blank=True)),
                ('calificacion', models.FloatField(blank=True, help_text='Calificación del audio de 0 a 100', null=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='evaluaciones.bloqueactividad')),
                ('intento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios_intento', to='evaluaciones.intentoactividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios_bloque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de Audio de Bloque',
                'verbose_name_plural': 'Entregas de Audio de Bloque',
            },
        ),
    ]
