# Generated by Django 5.1.3 on 2026-07-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0010_actividadvirtual_bloqueactividad_intentoactividad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentesesion',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterModelOptions(
            name='preguntasimulacro',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sesionsimulacro',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterModelOptions(
            name='simulacro',
            options={'ordering': ['orden', 'id']},
        ),
    ]
