# Generated by Django 5.1.3 on 2026-07-27 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0038_alumno_usuario'),
        ('evaluaciones', '0011_alter_componentesesion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTallerGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está marcado, los alumnos de este grupo presencial verán este examen/taller para realizar.')),
                ('intentos_permitidos', models.PositiveIntegerField(default=1, help_text='Por defecto 1 intento para evaluaciones presenciales en aula.')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres_asignados', to='academico.grupo')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_grupo', to='evaluaciones.taller')),
            ],
            options={
                'verbose_name': 'Asignación de Taller a Grupo',
                'verbose_name_plural': 'Asignaciones de Talleres a Grupos',
                'unique_together': {('taller', 'grupo')},
            },
        ),
    ]
