# Generated by Django 5.1.3 on 2026-07-29 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0006_modulo_activo'),
        ('evaluaciones', '0012_asignaciontallergrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='modulo',
            field=models.ForeignKey(blank=True, help_text='Módulo del programa virtual opcional. Dejar en blanco para talleres presenciales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres', to='curriculo.modulo'),
        ),
    ]
