# Generated by Django 5.1.3 on 2026-07-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0040_clase_taller_cerrado_clase_taller_notas_liberadas'),
        ('evaluaciones', '0013_alter_taller_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentotaller',
            name='clase',
            field=models.ForeignKey(blank=True, help_text='Clase presencial asociada a este intento de taller.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_taller', to='academico.clase'),
        ),
    ]
