# Generated by Django 5.1.3 on 2025-02-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], max_length=2)),
                ('nombres_tutor', models.CharField(max_length=100)),
                ('primer_apellido_tutor', models.CharField(max_length=100)),
                ('segundo_apellido_tutor', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_tutor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, help_text='Regla de código:\n                            3 letras de la ciudad + 3 letras de la sede + codigo de 2 numeros + una letra \n                            (opcional por si) hay un salon gemelo', max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
