# Generated by Django 5.1.3 on 2025-02-05 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('ubicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clase',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='ubicaciones.salon'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='ubicaciones.salon'),
        ),
        migrations.AddField(
            model_name='clase',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='academico.grupo'),
        ),
        migrations.AddField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='academico.materia'),
        ),
    ]
