# Generated by Django 5.1.3 on 2025-02-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alumno_grupo_actual_asistencia_nota'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='ubicaciones.municipio'),
        ),
    ]
