# Generated by Django 5.1.3 on 2025-02-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alumno_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='horario',
        ),
        migrations.AddField(
            model_name='clase',
            name='horario',
            field=models.CharField(choices=[('08:00-10:00', '8:00 AM - 10:00 AM'), ('10:00-12:00', '10:00 AM - 12:00 PM'), ('15:00-17:00', '3:00 PM - 5:00 PM'), ('08:00-17:00', '8:00 AM - 5:00 PM (Simulacro)')], default=None, help_text='Seleccione el horario de la clase.', max_length=20),
        ),
    ]
