# Generated by Django 5.1.3 on 2025-02-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_clase_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='celular',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='celular_tutor',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombres_tutor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='primer_apellido_tutor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
