# Generated by Django 5.1.3 on 2025-02-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_alter_alumno_celular_alter_alumno_celular_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='identificacion',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
