# Generated by Django 5.1.3 on 2025-02-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_alter_clase_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateField(),
        ),
    ]
