# Generated by Django 5.1.3 on 2025-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_alter_clase_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='celular_tutor',
            new_name='celular_madre',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='nombres_tutor',
            new_name='nombres_madre',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='primer_apellido_tutor',
            new_name='nombres_padre',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='segundo_apellido_tutor',
            new_name='primer_apellido_madre',
        ),
        migrations.AddField(
            model_name='alumno',
            name='celular_padre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='primer_apellido_padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='segundo_apellido_madre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='segundo_apellido_padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
