# Generated by Django 5.1.3 on 2025-03-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_rename_celular_tutor_alumno_celular_madre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('vista', 'Vista'), ('cancelada', 'Cancelada')], default='programada', help_text='Estado de la clase.', max_length=20),
        ),
    ]
