# Generated by Django 5.1.3 on 2025-04-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0017_alter_nota_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='es_becado',
            field=models.BooleanField(default=False, help_text='Marcar si el estudiante tiene beca', verbose_name='¿Es becado?'),
        ),
    ]
