# Generated by Django 5.1.3 on 2025-04-12 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_alter_clase_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_culminacion',
            field=models.DateField(default=datetime.date(2025, 8, 8), help_text='Fecha en que el alumno culmina su estancia en el preicfes', verbose_name='Fecha de culminación'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2025, 1, 1), help_text='Fecha en que el alumno ingresó al preicfes', verbose_name='Fecha de ingreso'),
        ),
    ]
