# Generated by Django 5.1.3 on 2025-04-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_alter_clase_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', help_text='Estado actual del alumno en el preicfes', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_retiro',
            field=models.DateField(blank=True, help_text='Fecha en que el alumno se retiró del preicfes', null=True, verbose_name='Fecha de retiro'),
        ),
    ]
