# Generated by Django 5.1.3 on 2025-05-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0023_alter_clase_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='codigo',
            field=models.CharField(blank=True, help_text='Regla de código:\n                            3 letras de la ciudad + 3 letras de la sede + codigo de 2 numeros + una letra \n                            (opcional por si) hay un salon gemelo', max_length=20, unique=True),
        ),
    ]
