# Generated by Django 5.1.3 on 2025-05-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0024_alter_grupo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tipo_programa',
            field=models.CharField(choices=[('pre_privado', 'PreICFES Privado'), ('pre_publico', 'PreICFES Público'), ('politecnico', 'Politécnico'), ('semillero', 'Semillero de Investigación')], default='pre_privado', help_text='Programa al que pertenece el estudiante', max_length=20, verbose_name='Tipo de Programa'),
        ),
    ]
