# Generated by Django 5.1.3 on 2025-08-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0025_alumno_tipo_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tipo_programa',
            field=models.CharField(choices=[('pre_privado', 'PreICFES Privado'), ('pre_publico', 'PreICFES Público'), ('premedico', 'PreMédico'), ('formacion_laboral', 'Formación Laboral'), ('semillero', 'Semillero de Investigación'), ('preicfes_kids', 'PreICFES Kids')], default='pre_privado', help_text='Programa al que pertenece el estudiante', max_length=20, verbose_name='Tipo de Programa'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='horario',
            field=models.CharField(choices=[('08:00-11:00', '8:00 AM - 11:00 AM'), ('14:00-17:00', '2:00 PM - 5:00 PM'), ('08:00-10:00', '8:00 AM - 10:00 AM'), ('10:00-12:00', '10:00 AM - 12:00 PM'), ('15:00-17:30', '3:00 PM - 5:30 PM'), ('18:45-20:45', '6:45 PM - 8:45 PM'), ('13:30-15:30', '1:30 PM - 3:30 PM'), ('15:30-17:30', '3:30 PM - 5:30 PM'), ('08:00-12:00', '8:00 AM - 12:00 PM (Medio Simulacro)'), ('08:00-17:00', '8:00 AM - 5:00 PM (Simulacro Completo)'), ('07:00-14:00', '7:00 AM - 2:00 PM (Jornada Especial Colegios)')], default=None, help_text='Seleccione el horario de la clase.', max_length=20),
        ),
    ]
