# Generated by Django 5.1.3 on 2025-09-27 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0026_alter_alumno_tipo_programa_alter_clase_horario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tipo_programa',
            field=models.CharField(choices=[('pre_privado', 'PreICFES Privado'), ('pre_publico', 'PreICFES Público'), ('premedico', 'PreMédico'), ('formacion_laboral', 'Formación Laboral'), ('semillero', 'Semillero de Investigación'), ('preicfes_kids', 'PreICFES Kids'), ('preicfes_virtual', 'PreICFES Virtual')], default='pre_privado', help_text='Programa al que pertenece el estudiante', max_length=20, verbose_name='Tipo de Programa'),
        ),
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, help_text='Razón de la inasistencia (ej. cita médica, calamidad, etc.)', null=True)),
                ('justificada', models.BooleanField(default=False, help_text='Marcar si la inasistencia fue justificada con un soporte válido.')),
                ('soporte', models.ImageField(blank=True, help_text='Imagen de soporte para la justificación (ej. excusa médica).', null=True, upload_to='soportes_inasistencias/%Y/%m/%d/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='academico.alumno')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='academico.clase')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inasistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inasistencia',
                'verbose_name_plural': 'Inasistencias',
                'ordering': ['-clase__fecha', 'alumno'],
                'unique_together': {('clase', 'alumno')},
            },
        ),
    ]
