# Generated by Django 5.1.3 on 2025-12-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0028_alter_clase_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='frecuencia_pago',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', help_text='Frecuencia con la que el estudiante realiza los pagos', max_length=20, verbose_name='Frecuencia de Pago'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tipo_identificacion',
            field=models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], default='TI', max_length=2),
        ),
    ]
