# Generated by Django 5.1.3 on 2026-02-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0029_alumno_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tipo_programa',
            field=models.CharField(choices=[('pre_privado', 'PreICFES Privado'), ('pre_publico', 'PreICFES Público'), ('premedico', 'PreMédico'), ('formacion_laboral', 'Formación Laboral'), ('semillero', 'Semillero de Investigación'), ('preicfes_kids', 'PreICFES Kids'), ('preicfes_virtual', 'PreICFES Virtual'), ('preicfes_vacacional', 'PreICFES Vacacional'), ('bachillerato_por_ciclos', 'Bachillerato por ciclos')], default='pre_privado', help_text='Programa al que pertenece el estudiante', max_length=30, verbose_name='Tipo de Programa'),
        ),
    ]
