# Generated by Django 5.1.3 on 2026-03-04 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0030_alter_alumno_tipo_programa'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='celular',
            field=models.CharField(default='SIN DATOS', max_length=15),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='celular_madre',
            field=models.CharField(default='SIN DATOS', max_length=15),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='celular_padre',
            field=models.CharField(default='SIN DATOS', max_length=15),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='frecuencia_pago',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], help_text='Frecuencia con la que el estudiante realiza los pagos', max_length=20, verbose_name='Frecuencia de Pago'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grupo_actual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_actuales', to='academico.grupo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='identificacion',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='ubicaciones.municipio'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombres_madre',
            field=models.CharField(default='SIN DATOS', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombres_padre',
            field=models.CharField(default='SIN DATOS', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='primer_apellido_madre',
            field=models.CharField(default='SIN DATOS', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='primer_apellido_padre',
            field=models.CharField(default='SIN DATOS', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='segundo_apellido_madre',
            field=models.CharField(default='SIN DATOS', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='segundo_apellido_padre',
            field=models.CharField(default='SIN DATOS', max_length=100),
        ),
    ]
