# Generated by Django 5.1.3 on 2026-03-04 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0031_alter_alumno_celular_alter_alumno_celular_madre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grupo_actual',
            field=models.ForeignKey(default=90, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_actuales', to='academico.grupo'),
        ),
    ]
