# Generated by Django 5.1.3 on 2026-03-04 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0032_alter_alumno_grupo_actual'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grupo_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_actuales', to='academico.grupo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='identificacion',
            field=models.CharField(help_text='Identificación del alumno (solo números, NO PUNTOS, NO COMAS, NO ESPACIOS)', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='ubicaciones.municipio'),
        ),
    ]
