# Generated by Django 5.1.3 on 2026-03-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0033_alter_alumno_grupo_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('limbo', 'Limbo')], default='activo', help_text='Estado actual del alumno en el preicfes', max_length=10, verbose_name='Estado'),
        ),
    ]
