# Generated by Django 5.1.15 on 2026-04-18 14:15

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0034_alter_alumno_estado"),
        ("academico", "0034_alumno_vendedor"),
    ]

    operations = [
    ]