# Generated by Django 5.1.15 on 2026-05-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0035_merge_0034_alter_alumno_estado_0034_alumno_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='tipo_programa',
            field=models.CharField(choices=[('pre_privado', 'PreICFES Privado'), ('pre_publico', 'PreICFES Público'), ('premedico', 'PreMédico'), ('formacion_laboral', 'Formación Laboral'), ('semillero', 'Semillero de Investigación'), ('preicfes_kids', 'PreICFES Kids'), ('preicfes_virtual', 'PreICFES Virtual'), ('preicfes_vacacional', 'PreICFES Vacacional'), ('bachillerato_por_ciclos', 'Bachillerato por ciclos'), ('curso_ingles', 'Curso de Inglés')], default='pre_privado', help_text='Programa al que pertenece el estudiante', max_length=30, verbose_name='Tipo de Programa'),
        ),
    ]
