# Generated by Django 5.1.3 on 2026-07-27 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0037_alter_alumno_tipo_programa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta de acceso del estudiante a la plataforma virtual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL),
        ),
    ]
