# Generated by Django 5.1.3 on 2026-07-28 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0038_alumno_usuario'),
        ('evaluaciones', '0012_asignaciontallergrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='taller',
            field=models.ForeignKey(blank=True, help_text='Taller interactivo opcional asignado a esta clase presencial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_presenciales', to='evaluaciones.taller'),
        ),
    ]
