# Generated by Django 5.1.3 on 2026-07-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0039_clase_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='taller_cerrado',
            field=models.BooleanField(default=False, help_text='True cuando el docente realiza el corte y cierra la recepción de respuestas del taller presencial.'),
        ),
        migrations.AddField(
            model_name='clase',
            name='taller_notas_liberadas',
            field=models.BooleanField(default=False, help_text='True cuando el docente libera las notas y solucionario para los estudiantes.'),
        ),
    ]
