# Generated by Django 5.1.3 on 2026-03-01 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creador',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró a esta persona (ej. Admin/Secretaría)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
