# Generated by Django 5.1.3 on 2026-03-01 21:58

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
    ]
