# Generated by Django 5.1.3 on 2026-03-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de identificación legal', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=3),
        ),
    ]
