# Generated by Django 4.2.16 on 2026-03-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('virtual_student', 'VirtualStudent')], default='student', max_length=20),
        ),
    ]
