# Generated by Django 4.2.16 on 2026-03-12 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentanaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio de apertura')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de cierre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventanas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
