# Generated by Django 4.2.16 on 2026-03-15 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_documento',
            field=models.CharField(default=0, help_text='Número de identificación legal', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento solo debe contener números, sin puntos ni espacios.', regex='^\\d+$')]),
            preserve_default=False,
        ),
    ]
