# Generated by Django 4.2.16 on 2026-03-15 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(default=0, help_text='Número de teléfono celular (10 dígitos)', max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos, sin comas, puntos ni espacios.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
