# Generated by Django 4.2.16 on 2026-05-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_whatsappresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_menu', models.CharField(choices=[('teal', 'Original (Oscuro-Teal)'), ('gold', 'Proyecto 500 (Negro-Dorado)'), ('christmas', 'Navidad (Rojo-Verde)')], default='teal', help_text='Paleta de colores para el menú lateral.', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración de la Plataforma',
                'verbose_name_plural': 'Configuraciones de la Plataforma',
            },
        ),
    ]
