# Generated by Django 4.2.16 on 2026-05-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_configuracionplataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplataforma',
            name='tema_menu',
            field=models.CharField(choices=[('teal', 'Original (Oscuro-Teal)'), ('gold', 'Proyecto 500 (Negro-Dorado)'), ('christmas', 'Navidad (Rojo-Verde)'), ('colombia', 'Bandera de Colombia (Amarillo-Azul-Rojo)')], default='teal', help_text='Paleta de colores para el menú lateral.', max_length=20),
        ),
    ]
