# Generated by Django 5.1.3 on 2026-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_configuracionplataforma_tema_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplataforma',
            name='tema_menu',
            field=models.CharField(choices=[('teal', 'Original (Oscuro-Teal)'), ('gold', 'Proyecto 500 (Negro-Dorado)'), ('christmas', 'Navidad (Rojo-Verde)'), ('colombia', 'Bandera de Colombia'), ('colombiaportu', 'Colombia + Portugal'), ('escociabrasil', 'Escocia + Brasil'), ('ecualemania', 'Ecuador + Alemania'), ('japonsuecia', 'Japón + Suecia'), ('uruguayespana', 'Uruguay + España')], default='teal', help_text='Paleta de colores para el menú lateral.', max_length=20),
        ),
    ]
