# Generated by Django 5.1.3 on 2026-06-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_configuracionplataforma_tema_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplataforma',
            name='tema_menu',
            field=models.CharField(choices=[('teal', 'Original (Oscuro-Teal)'), ('gold', 'Proyecto 500 (Negro-Dorado)'), ('christmas', 'Navidad (Rojo-Verde)'), ('brasiljap', 'Brasil vs Japón'), ('colombiaghana', 'Colombia vs Ghana'), ('franciasuecia', 'Francia vs Suecia'), ('portucroacia', 'Portugal vs Croacia'), ('argcaboverde', 'Argentina vs Cabo Verde'), ('inglatcongo', 'Inglaterra vs Congo'), ('espanaustria', 'España vs Austria')], default='teal', help_text='Paleta de colores para el menú lateral.', max_length=20),
        ),
    ]
