# Generated by Django 5.1.3 on 2026-07-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_configuracionplataforma_tema_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionplataforma',
            name='tema_menu',
            field=models.CharField(choices=[('teal', 'Original (Oscuro-Teal)'), ('gold', 'Proyecto 500 (Negro-Dorado)'), ('christmas', 'Navidad (Rojo-Verde)'), ('suizacolombia', 'Suiza vs Colombia'), ('portespana', 'Portugal vs España'), ('mexicoinglat', 'México vs Inglaterra'), ('brasilnoruega', 'Brasil vs Noruega'), ('argegipo', 'Argentina vs Egipto')], default='teal', help_text='Paleta de colores para el menú lateral.', max_length=20),
        ),
    ]
