# Generated by Django 5.1.3 on 2026-07-06 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0005_alter_modulo_ciclo'),
        ('usuarios', '0014_alter_configuracionplataforma_tema_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='programa',
            field=models.ForeignKey(blank=True, help_text='Programa asignado al estudiante (rol: student/virtual_student)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_inscritos', to='curriculo.programa'),
        ),
        migrations.AddField(
            model_name='user',
            name='programas_docente',
            field=models.ManyToManyField(blank=True, help_text='Programas a los que el profesor tiene acceso (rol: teacher)', related_name='profesores_inscritos', to='curriculo.programa'),
        ),
    ]
