# Generated by Django 5.1.3 on 2026-07-27 23:10

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_colegio'),
        ('usuarios', '0015_user_programa_user_programas_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='ubicaciones.departamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='ubicaciones.municipio'),
        ),
        migrations.AddField(
            model_name='user',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='ubicaciones.sede'),
        ),
        migrations.AlterField(
            model_name='configuracionplataforma',
            name='tema_menu',
            field=models.CharField(choices=[('teal', 'Original (Oscuro-Teal)'), ('gold', 'Proyecto 500 (Negro-Dorado)'), ('christmas', 'Navidad (Rojo-Verde)'), ('franciainglat', 'Francia vs Inglaterra'), ('espanaarg', 'España vs Argentina')], default='teal', help_text='Paleta de colores para el menú lateral.', max_length=20),
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de la firma digital (PNG transparente)', upload_to=usuarios.models.firma_upload_path)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmas',
            },
        ),
    ]
