# Generated by Django 5.1.3 on 2026-07-28 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_user_departamento_user_municipio_user_sede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de identificación legal', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento solo debe contener números, sin puntos ni espacios.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono celular', max_length=20, null=True),
        ),
    ]
