# Generated by Django 5.1.3 on 2026-08-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
