# Generated by Django 5.1.3 on 2026-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_remove_role_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto o avatar del perfil', null=True, upload_to='perfiles/', verbose_name='Foto de perfil'),
        ),
    ]
