# Generated by Django 5.1.3 on 2026-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto/Párrafo'), ('imagen', 'Imagen/GIF'), ('youtube', 'Video de YouTube'), ('enlace', 'Enlace Externo')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('contenido_texto', models.TextField(blank=True, help_text='Para bloques de texto', null=True)),
                ('archivo_imagen', models.ImageField(blank=True, help_text='Para imágenes o GIFs', null=True, upload_to='contenidos/bloques/')),
                ('url', models.URLField(blank=True, help_text='Para YouTube o enlaces externos', null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('publicado', 'Publicado'), ('oculto', 'Oculto')], default='borrador', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el módulo o semana')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['modulo', 'orden'],
            },
        ),
    ]
