# Generated by Django 4.2.16 on 2026-03-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_start_date', models.DateField(help_text='Fecha de inicio por defecto para nuevas suscripciones automáticas')),
                ('default_end_date', models.DateField(help_text='Fecha de fin por defecto para nuevas suscripciones automáticas')),
                ('active', models.BooleanField(default=True, help_text='Marcar para usar esta configuración (solo una debería estar activa)')),
            ],
            options={
                'verbose_name': 'Configuración de Suscripción',
                'verbose_name_plural': 'Configuraciones de Suscripciones',
            },
        ),
    ]
