# Generated by Django 5.1.3 on 2026-06-29 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_subscriptionconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', '-id'], name='suscripcion_user_id_2bfab7_idx'),
        ),
    ]
