# Generated by Django 5.1.3 on 2026-07-05 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_ciclo_programa_remove_modulo_activo_modulo_ciclo_and_more'),
        ('suscripciones', '0004_subscription_suscripcion_user_id_2bfab7_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor'), ('monitor', 'Monitor')], default='student', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='curriculo.programa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('user', 'programa')},
            },
        ),
    ]
