# Generated by Django 5.1.3 on 2026-07-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0005_inscripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscripcion',
        ),
    ]
