# Generated by Django 5.1.3 on 2026-06-29 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colegios', to='ubicaciones.municipio')),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'ordering': ['municipio__departamento__nombre', 'municipio__nombre', 'nombre'],
                'unique_together': {('nombre', 'municipio')},
            },
        ),
    ]
