def contar_coincidencias(cadena1, cadena2):
    """Versión simplificada que solo devuelve el número de coincidencias."""
    return sum(1 for i in range(min(len(cadena1), len(cadena2))) if cadena1[i] == cadena2[i])

r1 = "BDCCBCBDBBBABCBCCBBDADDABDBACCDBDAABDCDBDDBBACCADACADBCBDCDCACBDBABAAABBBDDABDADCBCDACABBCCCBBDCCDCCCBCBDBCDBBBACACAADBC"

# Uso rápido
resultado = contar_coincidencias(
    "BDCCBCBDBBBABCBCCBBDADDABDBACCDBDAABDCDBDDZZACCADACADBCBDCDCACBDBABAAABBBDDABDADCBCDACABBCCCBBDCCDCCCBCBDBCDBBBACACAADBC", 
    "BDCCBCBDBBBABCBCCBBDADDABDBACCDBDAABDCDBDDBBACCADACADBCBDCDCACBDBABAAABBBDDABDADCBCDACABBCCCBBDCCDCCCBCBDBCDBBBACACAADBC"
    )
print(f"Coincidencias: {resultado}")