# Generated by Django 5.1.3 on 2026-07-05 23:10

import django.db.models.deletion
from django.db import migrations, models


def crear_preicfes_y_asignar(apps, schema_editor):
    """
    Crea el Programa PreICFES, un Ciclo inicial, y asigna
    todos los Modulos y Materias existentes a ellos.
    """
    Programa = apps.get_model('curriculo', 'Programa')
    Ciclo    = apps.get_model('curriculo', 'Ciclo')
    Modulo   = apps.get_model('curriculo', 'Modulo')
    Materia  = apps.get_model('curriculo', 'Materia')

    preicfes = Programa.objects.create(
        nombre='PreICFES Victor Valdez',
        tipo='preicfes',
        slug='preicfes',
        activo=True,
        descripcion='Programa de preparación para el ICFES Saber 11.',
    )
    ciclo = Ciclo.objects.create(
        programa=preicfes,
        nombre='Ciclo Actual',
        orden=1,
        visible=True,
    )
    # Asignar todos los módulos existentes al ciclo
    Modulo.objects.all().update(ciclo=ciclo)
    # Asignar todas las materias existentes al programa preicfes
    for materia in Materia.objects.all():
        materia.programas.add(preicfes)


def revertir_preicfes(apps, schema_editor):
    """Reversa: borra el programa preicfes (cascada elimina el Ciclo)."""
    Programa = apps.get_model('curriculo', 'Programa')
    Programa.objects.filter(slug='preicfes').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_remove_clasevirtual_fecha_programada_and_more'),
    ]

    operations = [
        # 1. Crear Programa y Ciclo (sin FK entre sí todavía)
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('preicfes', 'PreICFES'), ('ingles', 'Inglés'), ('bachillerato', 'Bachillerato por Ciclos')], default='preicfes', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True, help_text='Si está visible para los estudiantes del programa')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='curriculo.programa')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['orden'],
            },
        ),
        # 2. Quitar activo de Modulo
        migrations.RemoveField(
            model_name='modulo',
            name='activo',
        ),
        # 3. Añadir ciclo como nullable primero
        migrations.AddField(
            model_name='modulo',
            name='ciclo',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='modulos', to='curriculo.ciclo',
            ),
        ),
        # 4. Añadir M2M programas a Materia
        migrations.AddField(
            model_name='materia',
            name='programas',
            field=models.ManyToManyField(
                blank=True,
                help_text='Programas en los que se usa esta materia',
                related_name='materias',
                to='curriculo.programa',
            ),
        ),
        # 5. Poblar datos: crear PreICFES + Ciclo Actual + asignar todo
        migrations.RunPython(crear_preicfes_y_asignar, revertir_preicfes),
        # 6. Hacer ciclo NOT NULL ahora que todos los registros están rellenos
        migrations.AlterField(
            model_name='modulo',
            name='ciclo',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='modulos', to='curriculo.ciclo',
            ),
        ),
    ]
