# Generated by Django 5.1.3 on 2026-07-06 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_ciclo_programa_remove_modulo_activo_modulo_ciclo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='curriculo.ciclo'),
        ),
    ]
