# Generated by Django 5.1.3 on 2026-07-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0005_alter_modulo_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desmarcado, los estudiantes no podrán ver este módulo.'),
        ),
    ]
